[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "simple-orbital-mechanics"
dynamic = ["version"]
authors = [
  { name="Jack Gale", email="jackkgale@gmail.com" },
]
description = "A small orbital mechanics library."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Galoose/orbital_mechanics"

[tool.hatch.version]
path = "src/simple_orbital_mechanics/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/simple_orbital_mechanics"]

[tool.hatch.build.targets.wheel.force-include]
"src/simple_orbital_mechanics/py.typed" = "simple_orbital_mechanics/py.typed"